### ISSUE TITLE
UnicodeEncodeError

### ISSUE THREAD

**Issue by ty-a** [hairr/chatbot#1]
![image](https://f.cloud.github.com/assets/1883388/77054/0af9a904-6113-11e2-8024-fbd44a8bfc15.png)

**Comment by hairr** [comment]
I fixed the UnicodeEncodeError, with the version 1.0.4a.  It was a simple string_escape decoding, this will fix the issue when printing the text.

Just, for quick reference to the code:

```
var = string.decode('string_escape')
```

This will return a string in 2.X but bytes in 3.X.
